### ISSUE TITLE
Speichern von Custom Types ist defekt in 2019.4

### ISSUE THREAD

**Issue by derUli** [derUli/ulicms#883]
Reproduzierbar mit custom_types_example.
Produkt-Seite anlegen, speichern => 

```
UliCMS\Exceptions\SqlException: Column 'value' cannot be null in /var/www/html/classes/objects/database/Database.php:95
Stack trace:
#0 /var/www/html/classes/objects/database/Database.php(152): Database::query('INSERT INTO tes...', true)
#1 /var/www/html/classes/objects/content/CustomFields.php(51): Database::pQuery('INSERT INTO {pr...', Array, true)
#2 /var/www/html/content/modules/core_content/controllers/PageController.php(232): CustomFields::set('product_product...', NULL, 15723, false)
#3 /var/www/html/content/modules/core_content/controllers/PageController.php(47): PageController->fillAndSaveModel(Object(Page), Object(UliCMS\Security\PermissionChecker), 13, 2)
#4 /var/www/html/classes/objects/abstract/Controller.php(42): PageController->editPost()
#5 /var/www/html/classes/objects/registry/ControllerRegistry.php(59): Controller->runCommand()
#6 /var/www/html/admin/backend.php(64): ControllerRegistry::runMethods()
#7 /var/www/html/admin/index.php(3): require_once('/www/htdocs/w00...')
#8 {main}
```

**Comment by derUli** [comment]
fixed
